### PR TITLE
Support for symfony 6

### PR DESCRIPTION
**Pull request by GeoDpto**
| Q               | A
| --------------- | ---
| Bug fix?        | no|yes
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| Documentation   |
| License         | MIT

#### What's in this PR?

Support for symfony 6.

### CODE REVIEW

**Comment by dbu** [comment]
thanks!

i realized that the CI no longer worked. i fixed it in the master branch - can you please rebase and add an entry in the .github/workflow/tests.yml for the new symfony version?

**Comment by dbu** [comment]
weird, the build succeeded with the old symfony constraint: https://github.com/php-http/stopwatch-plugin/actions/runs/1543787287

oh wait, i missed to actually apply the constraint :see_no_evil: - can you rebase on master again please? after that, the symfony 5 build should no longer fail, i think.

**Comment by GeoDpto** [comment]
```phpspec/phpspec``` package is not compatible with SF 6 :(

We need to wait while the package will update to the new version.
https://github.com/phpspec/phpspec/pull/1402

**Comment by dbu** [comment]
i fear you are right. lets hope they can release an updated version soon. my guess is that we would not have any issues in this plugin, but i'd rather not merge without knowing.

**Comment by ruudk** [comment]
What about removing PHPSpec and just use a good old PHPUnit test?

I mean, look at this small spec test: https://github.com/php-http/stopwatch-plugin/blob/master/spec/StopwatchPluginSpec.php
No need to keep this blocked if you ask me.

**Comment by ruudk** [comment]
Discussed with @Nyholm and decided to drop PHPSpec. Did that in https://github.com/php-http/stopwatch-plugin/pull/21. When that is merged you can rebase.

**Comment by ruudk** [comment]
Rebased this PR in https://github.com/php-http/stopwatch-plugin/pull/22 , so that we can merge and tag it!

**Comment by dbu** [comment]
merged in #22. thanks a lot @GeoDpto and @ruudk

**Pull request closed without merging**
